project:
  type: website
    twitter-card: true
  output-dir: docs

website:
  title: "Sun and Sea"
  navbar:
    right:
      - about.qmd
      - text: Blog
        href: index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/Rogers_M_P
format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

