---
title: "Young Scientist"
author: "MP Rogers"
date: 2/12/2023
format: html
editor: visual
categories:
  - Marine Biology
---

## 

So this one is intended to be a little more of a personal post, not necessarily as data heavy or marine biology heavy as the others. This post is actually one I've been contemplating since starting up a blog. This one is designed to be a little "review" of what its been like to be a young Jamaican scientist, a year after graduating. This has been my experience, but hopefully its also something you can learn from. I suspect its also not limited to Jamaica.

## A Little Context

So my graduation was November 2022, and this post is being written in December 2023. So its roughly been a year since I graduated from the [University of the West Indies](https://www.mona.uwi.edu/). My major was in Marine Biology with a minor in Economics. A good chunk of this degree took place during the Covid Pandemic, meaning a good chunk of courses were online, at least partially.

## Overall

Honestly, Overall I'd say its been a fun ride. I chose the field because I was inspired and passionate about it. That hasn't changed. I'm still a marine biologist because it gets me going. That said, I'd be lying if I said I hadn't considered switching to something more "mainstream", even if just for a while. I'd be lying if I said I didn't still get those thoughts now. That being said, after a year, I think I have enough experience to share to those considering a similar path in Jamaica. My journey is still just starting, but you get an opinion from one who's taken their first steps.

## 

## Brief Summary

So, Just to give a brief rundown of the last year. Since graduating, I've started work with a Start-up in my field. There's other posts around the blog (see here) about stuff i've done with the company. The start-up is [Kee Farms](https://www.keefarms.com/), a relatively young company aiming to combat climate change through regenerative ocean farming. The company is young as well, so it's as much of a leaning curve for me as it is for them. I've learned more about how things are done than the technical marine biology here.

I've also done an internship with the [Discovery Bay Marine Lab](https://www.mona.uwi.edu/cms/dbml.htm). This lab is located in St Ann, Jamaica. The lab has an internship program taking in two cycles of interns per year. Normally these include the recent graduates from the Marine Biology program at the University of the West Indies, but it is open to interested international students. This was one of my first times away from home for so long. It was also a chance to work with more seasoned Marine Biologists. The lab taught us quite a few skills and tools, but they also exposed us to reseach, teaching and outreach. In the process, the interns could get a feel of what worked best for us and what we gravitated towards.

Finally, in the process, I've decided on a rough area of marine biology I'm interested in. I've suspected for a while where in marine biology I'd love to focus on in an ideal world. I definitely

## What I Like

I'm in the field I'm passionate about.

I've managed to be on the water and in the water

I've done hands on, practical work

I can look back and see new skills I've cultivated over the year

## What I Don't Like

Getting funding is hard

There's not a ton of organisations out there so you may need to move more than you'd like

Politics is everywhere, including science

## What I'd Change/Advice

Keep Learning

Be more than just a scientist

The top supplementary Science Skills

A call to discuss with my Email/twitter DMs open

Feel free to follow up. If you have any Questions, message me on [Linkedln](www.linkedin.com/in/matthew-pierre-rogers-786362224), [Twitter](https://twitter.com/Rogers_M_P), or [my Email](mailto:matthewpierrerogers@gmail.com), and i will do my best to get back to you soon.

Walk Good and Happy New Year

## 
